version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    networks:
      - appnet
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 

networks:
  appnet:
    driver: bridge

